-- DEPARTMENT --
INSERT INTO Department VALUES ('CSE','COMPUTER SCIENCE AND ENGINEERING');
INSERT INTO Department VALUES ('PHY','PHYSICS');
-- PROGRAMME --
INSERT INTO Programme VALUES ('APPLIED DATA SCIENCE', 'ADS');
INSERT INTO Programme VALUES ('THEORETICAL PHYSICS IN MICROBIOLOGY','TPMB');
-- HOSTS --
INSERT INTO Hosts VALUES ('APPLIED DATA SCIENCE', 'CSE');
INSERT INTO Hosts VALUES ('APPLIED DATA SCIENCE', 'PHY');
INSERT INTO Hosts VALUES ('THEORETICAL PHYSICS IN MICROBIOLOGY', 'CSE');
-- COURSE --
INSERT INTO Course VALUES ('TDA357','DATABASES',9.6,'CSE');
INSERT INTO Course VALUES ('TDA356','INTRO TO DATABASES',7.5,'CSE');
-- CLASSIFICATION --
INSERT INTO Classification VALUES ('mathematical'),('research'),('seminar');
-- HAS --
INSERT INTO Has VALUES ('TDA357','mathematical'),('TDA357','research');
-- RESTRICTED COURSE --
INSERT INTO Restricted_Course VALUES ('TDA357',1);
-- STUDENTS --
INSERT INTO Students VALUES ('9004235556','2430013938','JIN GUO','APPLIED DATA SCIENCE');
INSERT INTO Students VALUES ('9004235557','2430013939','GIN JUO','APPLIED DATA SCIENCE');
-- BRANCHES --
INSERT INTO Branches VALUES ('Data Management', 'APPLIED DATA SCIENCE');
INSERT INTO Branches VALUES ('Data Engineering', 'APPLIED DATA SCIENCE');
-- READS --
INSERT INTO Reads VALUES ('9004235556','TDA357','4');
-- REGISTERS -- 
INSERT INTO Registers VALUES ('9004235556', 'TDA357');
-- WAITING LIST --
INSERT INTO Waiting_list VALUES ('TDA357','9004235556','1');
-- PICKS --
INSERT INTO Picks VALUES ('Data Management','APPLIED DATA SCIENCE','9004235556');
-- BRANCH RECOMMENDS --
INSERT INTO Br_Recommends VALUES ('Data Management','APPLIED DATA SCIENCE','TDA357');
-- BRANCH REQUIRES --
INSERT INTO Br_Requires VALUES ('Data Engineering', 'APPLIED DATA SCIENCE','TDA357');
-- PRE-REQUISITES --
INSERT INTO Pre_requires VALUES ('TDA357','TDA356');
-- PROGRAMME REQUIRES --
INSERT INTO Prog_requires VALUES ('APPLIED DATA SCIENCE','TDA357');




